language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<1.12"
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
  - pip install coveralls
script:
   - python -Wall `which coverage` run --omit='setup.py' --source=. tests/manage.py test core --settings=
after_success:
  - coveralls
